{{- $operatorValues := index .Values "materialize-operator" | required "missing materialize-operator from .Values" }}
{{- $fullname := printf "%s-materialize-operator" ( include "mzmon.fullname" . ) -}}
{{- if $operatorValues.serviceMonitor.enabled }}
  {{- $monitor := $.Files.Get "pre-rendered/scrapers/prometheus-operator/podmonitor-materialize-operator.yaml" | fromYaml }}

  {{- $newMetadata := ( dict
    "namespace" $operatorValues.namespace
    "name" $fullname
    "labels" ( include "mzmon.labels" $ | fromYaml )
    "annotations" ( include "mzmon.annotations" $ | fromYaml )
  ) }}
  {{- $_ := mergeOverwrite $monitor.metadata $newMetadata }}

  {{- if $operatorValues.serviceMonitor.selector }}
    {{- $_ := set $monitor.spec "selector" $operatorValues.serviceMonitor.selector }}
  {{- end }}
  {{- if $operatorValues.serviceMonitor.targetLabels }}
    {{- $_ := set $monitor.spec "podTargetLabels" $operatorValues.serviceMonitor.targetLabels }}
  {{- end }}
  {{- if $operatorValues.serviceMonitor.metricEndpoints }}
    {{- $_ := set $monitor.spec "podMetricsEndpoints" $operatorValues.serviceMonitor.metricEndpoints }}
  {{- end }}
  {{- toYaml $monitor | nindent 0 }}
{{- end }}
