{{- $materializeValues := .Values.materialize.clusterd | required "missing materialize.clusterd from .Values" }}
{{- if $materializeValues.serviceMonitor.enabled }}
  {{- $monitor := $.Files.Get "pre-rendered/scrapers/prometheus-operator/podmonitor-clusterd.yaml" | fromYaml }}

  {{- $fullname := printf "%s-materialize-clusterd" ( include "mzmon.fullname" . ) -}}
  {{- $newMetadata := ( dict
    "namespace" ( include "mzmon.namespace" $ )
    "name" $fullname
    "labels" ( include "mzmon.labels" $ | fromYaml )
    "annotations" ( include "mzmon.annotations" $ | fromYaml )
  ) }}
  {{- $_ := mergeOverwrite $monitor.metadata $newMetadata }}

  {{- if $materializeValues.serviceMonitor.selector }}
    {{- $_ := set $monitor.spec "selector" $materializeValues.serviceMonitor.selector }}
  {{- end }}
  {{- if $materializeValues.serviceMonitor.targetLabels }}
    {{- $_ := set $monitor.spec "podTargetLabels" $materializeValues.serviceMonitor.targetLabels }}
  {{- end }}
  {{- if $materializeValues.serviceMonitor.metricEndpoints }}
    {{- $_ := set $monitor.spec "podMetricsEndpoints" $materializeValues.serviceMonitor.metricEndpoints }}
  {{- end }}
  {{- toYaml $monitor | nindent 0 }}
{{- end }}
