{{- $materializeValues := .Values.materialize.environmentdSQL | required "missing materialize.environmentdSQL from .Values" }}
{{- if and $materializeValues.serviceMonitor.enabled $materializeValues.secret.create }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.materialize.environmentdSQL.secret.name }}
data:
  username: {{ .Values.materialize.environmentdSQL.secret.username | b64enc | quote }}
  password: {{ .Values.materialize.environmentdSQL.secret.password | b64enc | quote }}
{{- end }}
