{{- $materializeValues := .Values.materialize.environmentdSQL | required "missing materialize.environmentdSQL from .Values" }}
{{- if $materializeValues.serviceMonitor.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.materialize.environmentdSQL.secret.name }}
data:
  username: {{ .Values.materialize.environmentdSQL.secret.username | b64enc | quote }}
{{- end }}
