// Copyright Materialize, Inc. and contributors. All rights reserved.
//
// Use of this software is governed by the Business Source License
// included in the LICENSE file.
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0.

//! `gen-metric-tiers`: emit `metric-tiers.yaml` — registry metrics grouped by
//! importance — for the Helm gateway's per-destination allowlists.
//!
//! Shares the extraction/roll-up with `extract-metrics` (so importance reflects
//! the same file hints + overrides), but renders through the prefix-agnostic
//! [`tier_context`] and projects to the tiers shape rather than the docs shape.

use std::path::PathBuf;

use anyhow::Context;
use mzmon_lib::query::docgen::extract_metric_docs;
use mzmon_lib::query::model::QueryEngine;
use mzmon_lib::query::registry::QueryRegistry;
use mzmon_lib::query::render::tier_context;
use mzmon_lib::query::tiers::MetricTiers;

/// Header prepended to the generated file. Explains the non-obvious bits so a
/// reader of the checked-in artifact isn't surprised by the regex fragments.
const HEADER: &str = "\
# Generated by `mz-monitoring-build gen-metric-tiers`. DO NOT EDIT.
#
# Registry metrics grouped by importance (each metric appears at exactly its own
# level; the Helm gateway unions \"this tier and more important\" per destination,
# and treats the `all` destination tier as `.*` without reading this file).
#
# Entries are anchored-regex fragments matched against the metric name. A leading
# `(?:v2_)?mz_` matches both the converged (`mz_`) and legacy (`v2_mz_`) prefixes
# of the SQL-exporter metrics; other names are literal.
";

/// Arguments for the `gen-metric-tiers` command.
#[derive(clap::Args)]
pub struct GenMetricTiersArgs {
    /// Directory containing query-registry YAML files.
    #[arg(long, default_value = "packages/queries")]
    source_dir: PathBuf,

    /// Output path for the generated `metric-tiers.yaml`.
    #[arg(long)]
    out: PathBuf,
}

/// Entry point for `mz-monitoring-build gen-metric-tiers`.
pub fn gen_metric_tiers(args: GenMetricTiersArgs) -> anyhow::Result<()> {
    let registry = QueryRegistry::from_directory(&args.source_dir)
        .with_context(|| format!("loading query registry from {}", args.source_dir.display()))?;

    let ctx = tier_context(&registry, QueryEngine::PromQl);
    let outcome = extract_metric_docs(&registry, &ctx);
    for (id, err) in &outcome.errors {
        eprintln!("warning: skipped query {id}: {err}");
    }

    let tiers = MetricTiers::from_docs(&outcome.metrics);
    let body = tiers.to_yaml().context("serializing metric-tiers.yaml")?;
    let contents = format!("{HEADER}{body}");

    if let Some(parent) = args.out.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating {}", parent.display()))?;
    }
    std::fs::write(&args.out, contents)
        .with_context(|| format!("writing {}", args.out.display()))?;

    eprintln!(
        "wrote {} metrics ({} essential, {} recommended, {} extended, {} diagnostic) -> {}",
        tiers.len(),
        tiers.essential.len(),
        tiers.recommended.len(),
        tiers.extended.len(),
        tiers.diagnostic.len(),
        args.out.display()
    );
    Ok(())
}
