apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: materialize-sql-mz-frontier
  labels:
    app.kubernetes.io/part-of: materialize
    app.kubernetes.io/name: environmentd
    app.kubernetes.io/component: sql-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: environmentd
  endpoints:
  - port: internal-http
    interval: 60s
    path: /metrics/mz_frontier
    basicAuth:
      username: mz_support
  targetLabels:
    fromPod:
    - from: materialize.cloud/organization-name
      to: materialize_cloud_organization_name
    - from: materialize.cloud/organization-namespace
      to: materialize_cloud_organization_namespace
    - from: materialize.cloud/organization-id
      to: materialize_cloud_organization_id
    - from: cluster.environmentd.materialize.cloud/cluster-id
      to: cluster_environmentd_materialize_cloud_cluster_id
    - from: cluster.environmentd.materialize.cloud/replica-id
      to: cluster_environmentd_materialize_cloud_replica_id
