# Example of using IRSA (in EKS) to connect to AWS S3 for object storage

## YourThanosRole Role Trust Relationship:
# Version: "2012-10-17"
# Statement:
#   - Effect: Allow
#     Principal:
#       Federated: arn:aws:iam::012345678901:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/EKSAAAAAAABBBBBBBCCCCCCCC
#     Action: sts:AssumeRoleWithWebIdentity
#     Condition:
#       StringEquals:
#         oidc.eks.us-east-1.amazonaws.com/id/EKSAAAAAAABBBBBBBCCCCCCCC:aud: sts.amazonaws.com
#         oidc.eks.us-east-1.amazonaws.com/id/EKSAAAAAAABBBBBBBCCCCCCCC:sub: system:serviceaccount:monitoring:your-release-thanos-thanos

## ThanosBucketRW Policy:
# Version: "2012-10-17"
# Statement:
#   - Effect: Allow
#     Action:
#       - s3:ListBucket
#       - s3:GetBucketLocation
#     Resource: arn:aws:s3:::your-bucket-name
#   - Effect: Allow
#     Action:
#       - s3:GetObject
#       - s3:PutObject
#       - s3:DeleteObject
#     Resource: arn:aws:s3:::your-bucket-name/*


thanos:
  enabled: true
  global:
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::012345678901:role/YourThanosRole"
