apiVersion: monitoring.googleapis.com/v1
kind: ClusterPodMonitoring
metadata:
  name: cni-aws-vpc-metrics-1
  labels:
    app.kubernetes.io/part-of: materialize
    app.kubernetes.io/name: cni-aws-vpc
spec:
  selector:
    matchLabels:
      k8s-app: aws-node
  endpoints:
  - port: agentmetrics
    interval: 30s
    path: /metrics
