# Example of a values file using an existing grafana instance

tags:
  # Deploy remaining components, grafana.enabled will override the grafana install
  bundled-backends: true

grafana:
  # Disables bundled grafana. This takes precedence over tags.bundled-backends
  enabled: false

connections:
  grafana:
    # Define grafana-operator to use an existing grafana instance
    mode: external
    # Define the connection details
    external:
      url: https://grafana.example.com
      # You must set either apiKey secret or adminUser+adminPassword secrets
      apiKey:
        name: external-grafana-api-key
        key: apiKey
