global:
  evaluation_interval: 1m
  scrape_interval: 1m
  scrape_timeout: 10s
scrape_configs:
- job_name: podMonitor/clusterd/metrics
  metrics_path: /metrics
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - source_labels:
    - __meta_kubernetes_pod_label_cluster_environmentd_materialize_cloud_type
    - __meta_kubernetes_pod_labelpresent_cluster_environmentd_materialize_cloud_type
    regex: (cluster);true
    action: keep
  - source_labels:
    - __meta_kubernetes_pod_container_port_name
    regex: internal-http
    action: keep
  - source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
  - source_labels:
    - __meta_kubernetes_pod_container_name
    target_label: container
  - source_labels:
    - __meta_kubernetes_pod_name
    target_label: pod
  - source_labels:
    - __meta_kubernetes_pod_label_materialize_cloud_organization_name
    target_label: materialize_cloud_organization_name
  - source_labels:
    - __meta_kubernetes_pod_label_materialize_cloud_organization_namespace
    target_label: materialize_cloud_organization_namespace
  - source_labels:
    - __meta_kubernetes_pod_label_materialize_cloud_organization_id
    target_label: materialize_cloud_organization_id
  - source_labels:
    - __meta_kubernetes_pod_label_cluster_environmentd_materialize_cloud_cluster_id
    target_label: cluster_environmentd_materialize_cloud_cluster_id
  - source_labels:
    - __meta_kubernetes_pod_label_cluster_environmentd_materialize_cloud_replica_id
    target_label: cluster_environmentd_materialize_cloud_replica_id
- job_name: podMonitor/environmentd/metrics
  metrics_path: /metrics
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - source_labels:
    - __meta_kubernetes_pod_label_app_kubernetes_io_name
    - __meta_kubernetes_pod_labelpresent_app_kubernetes_io_name
    regex: (environmentd);true
    action: keep
  - source_labels:
    - __meta_kubernetes_pod_container_port_name
    regex: internal-http
    action: keep
  - source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
  - source_labels:
    - __meta_kubernetes_pod_container_name
    target_label: container
  - source_labels:
    - __meta_kubernetes_pod_name
    target_label: pod
  - source_labels:
    - __meta_kubernetes_pod_label_materialize_cloud_organization_name
    target_label: materialize_cloud_organization_name
  - source_labels:
    - __meta_kubernetes_pod_label_materialize_cloud_organization_namespace
    target_label: materialize_cloud_organization_namespace
  - source_labels:
    - __meta_kubernetes_pod_label_materialize_cloud_organization_id
    target_label: materialize_cloud_organization_id
  - source_labels:
    - __meta_kubernetes_pod_label_cluster_environmentd_materialize_cloud_cluster_id
    target_label: cluster_environmentd_materialize_cloud_cluster_id
  - source_labels:
    - __meta_kubernetes_pod_label_cluster_environmentd_materialize_cloud_replica_id
    target_label: cluster_environmentd_materialize_cloud_replica_id
- job_name: podMonitor/materialize-operator/metrics
  metrics_path: /metrics
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - source_labels:
    - __meta_kubernetes_pod_label_app_kubernetes_io_name
    - __meta_kubernetes_pod_labelpresent_app_kubernetes_io_name
    regex: (materialize-operator);true
    action: keep
  - source_labels:
    - __meta_kubernetes_pod_container_port_name
    regex: metrics
    action: keep
  - source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
  - source_labels:
    - __meta_kubernetes_pod_container_name
    target_label: container
  - source_labels:
    - __meta_kubernetes_pod_name
    target_label: pod
  - source_labels:
    - __meta_kubernetes_pod_label_materialize_cloud_organization_name
    target_label: materialize_cloud_organization_name
  - source_labels:
    - __meta_kubernetes_pod_label_materialize_cloud_organization_namespace
    target_label: materialize_cloud_organization_namespace
  - source_labels:
    - __meta_kubernetes_pod_label_materialize_cloud_organization_id
    target_label: materialize_cloud_organization_id
  - source_labels:
    - __meta_kubernetes_pod_label_cluster_environmentd_materialize_cloud_cluster_id
    target_label: cluster_environmentd_materialize_cloud_cluster_id
  - source_labels:
    - __meta_kubernetes_pod_label_cluster_environmentd_materialize_cloud_replica_id
    target_label: cluster_environmentd_materialize_cloud_replica_id
- job_name: podMonitor/materialize-sql/mz-compute
  metrics_path: /metrics/mz_compute
  basic_auth:
    username: mz_support
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - source_labels:
    - __meta_kubernetes_pod_label_app_kubernetes_io_name
    - __meta_kubernetes_pod_labelpresent_app_kubernetes_io_name
    regex: (environmentd);true
    action: keep
  - source_labels:
    - __meta_kubernetes_pod_container_port_name
    regex: internal-http
    action: keep
  - source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
  - source_labels:
    - __meta_kubernetes_pod_container_name
    target_label: container
  - source_labels:
    - __meta_kubernetes_pod_name
    target_label: pod
  - source_labels:
    - __meta_kubernetes_pod_label_materialize_cloud_organization_name
    target_label: materialize_cloud_organization_name
  - source_labels:
    - __meta_kubernetes_pod_label_materialize_cloud_organization_namespace
    target_label: materialize_cloud_organization_namespace
  - source_labels:
    - __meta_kubernetes_pod_label_materialize_cloud_organization_id
    target_label: materialize_cloud_organization_id
  - source_labels:
    - __meta_kubernetes_pod_label_cluster_environmentd_materialize_cloud_cluster_id
    target_label: cluster_environmentd_materialize_cloud_cluster_id
  - source_labels:
    - __meta_kubernetes_pod_label_cluster_environmentd_materialize_cloud_replica_id
    target_label: cluster_environmentd_materialize_cloud_replica_id
- job_name: podMonitor/materialize-sql/mz-frontier
  metrics_path: /metrics/mz_frontier
  basic_auth:
    username: mz_support
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - source_labels:
    - __meta_kubernetes_pod_label_app_kubernetes_io_name
    - __meta_kubernetes_pod_labelpresent_app_kubernetes_io_name
    regex: (environmentd);true
    action: keep
  - source_labels:
    - __meta_kubernetes_pod_container_port_name
    regex: internal-http
    action: keep
  - source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
  - source_labels:
    - __meta_kubernetes_pod_container_name
    target_label: container
  - source_labels:
    - __meta_kubernetes_pod_name
    target_label: pod
  - source_labels:
    - __meta_kubernetes_pod_label_materialize_cloud_organization_name
    target_label: materialize_cloud_organization_name
  - source_labels:
    - __meta_kubernetes_pod_label_materialize_cloud_organization_namespace
    target_label: materialize_cloud_organization_namespace
  - source_labels:
    - __meta_kubernetes_pod_label_materialize_cloud_organization_id
    target_label: materialize_cloud_organization_id
  - source_labels:
    - __meta_kubernetes_pod_label_cluster_environmentd_materialize_cloud_cluster_id
    target_label: cluster_environmentd_materialize_cloud_cluster_id
  - source_labels:
    - __meta_kubernetes_pod_label_cluster_environmentd_materialize_cloud_replica_id
    target_label: cluster_environmentd_materialize_cloud_replica_id
- job_name: podMonitor/materialize-sql/mz-storage
  metrics_path: /metrics/mz_storage
  basic_auth:
    username: mz_support
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - source_labels:
    - __meta_kubernetes_pod_label_app_kubernetes_io_name
    - __meta_kubernetes_pod_labelpresent_app_kubernetes_io_name
    regex: (environmentd);true
    action: keep
  - source_labels:
    - __meta_kubernetes_pod_container_port_name
    regex: internal-http
    action: keep
  - source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
  - source_labels:
    - __meta_kubernetes_pod_container_name
    target_label: container
  - source_labels:
    - __meta_kubernetes_pod_name
    target_label: pod
  - source_labels:
    - __meta_kubernetes_pod_label_materialize_cloud_organization_name
    target_label: materialize_cloud_organization_name
  - source_labels:
    - __meta_kubernetes_pod_label_materialize_cloud_organization_namespace
    target_label: materialize_cloud_organization_namespace
  - source_labels:
    - __meta_kubernetes_pod_label_materialize_cloud_organization_id
    target_label: materialize_cloud_organization_id
  - source_labels:
    - __meta_kubernetes_pod_label_cluster_environmentd_materialize_cloud_cluster_id
    target_label: cluster_environmentd_materialize_cloud_cluster_id
  - source_labels:
    - __meta_kubernetes_pod_label_cluster_environmentd_materialize_cloud_replica_id
    target_label: cluster_environmentd_materialize_cloud_replica_id
- job_name: podMonitor/materialize-sql/mz-usage
  metrics_path: /metrics/mz_usage
  basic_auth:
    username: mz_support
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - source_labels:
    - __meta_kubernetes_pod_label_app_kubernetes_io_name
    - __meta_kubernetes_pod_labelpresent_app_kubernetes_io_name
    regex: (environmentd);true
    action: keep
  - source_labels:
    - __meta_kubernetes_pod_container_port_name
    regex: internal-http
    action: keep
  - source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
  - source_labels:
    - __meta_kubernetes_pod_container_name
    target_label: container
  - source_labels:
    - __meta_kubernetes_pod_name
    target_label: pod
  - source_labels:
    - __meta_kubernetes_pod_label_materialize_cloud_organization_name
    target_label: materialize_cloud_organization_name
  - source_labels:
    - __meta_kubernetes_pod_label_materialize_cloud_organization_namespace
    target_label: materialize_cloud_organization_namespace
  - source_labels:
    - __meta_kubernetes_pod_label_materialize_cloud_organization_id
    target_label: materialize_cloud_organization_id
  - source_labels:
    - __meta_kubernetes_pod_label_cluster_environmentd_materialize_cloud_cluster_id
    target_label: cluster_environmentd_materialize_cloud_cluster_id
  - source_labels:
    - __meta_kubernetes_pod_label_cluster_environmentd_materialize_cloud_replica_id
    target_label: cluster_environmentd_materialize_cloud_replica_id
- job_name: mz-kubelet-cadvisor
  kubernetes_sd_configs:
  - role: node
  relabel_configs:
  - regex: __meta_kubernetes_node_label_(.+)
    action: labelmap
  - target_label: __address__
    replacement: kubernetes.default.svc:443
  - source_labels:
    - __meta_kubernetes_node_name
    target_label: __metrics_path__
    regex: (.+)
    replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
