apiVersion: monitoring.coreos.com/v1
# FIXME: switch to ServiceMonitor (can't distinguish by gen vs non-gen)
kind: PodMonitor
metadata:
  name: materialize-operator
  labels:
    app.kubernetes.io/part-of: materialize
    app.kubernetes.io/name: materialize-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: materialize-operator
  # https://prometheus-operator.dev/docs/api-reference/api/#monitoring.coreos.com/v1.PodMetricsEndpoint
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      relabelings: []
